'use client';
import { Inter } from 'next/font/google';
import { usePathname } from 'next/navigation';
import Navbar from './(components)/Navbar';
import GetInTouch from './(components)/GetInTouch';
import Footer from './(components)/Footer';
import './globals.css';
import 'aos/dist/aos.css';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import Scrollup from './(components)/scrollup';

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({ children }) {
  const pathname = usePathname();
  const isLoginPage = pathname === '/login';

  return (
    <html lang="en">
      <head>
        <title>wishgeekstechserve</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/wishi.svg" sizes="any" />
      </head>
      <body className={inter.className}>
       
        {!isLoginPage && <Navbar />}
        {children}
        <Scrollup/>
        {!isLoginPage && <GetInTouch />}
        {!isLoginPage && <Footer />}
      </body>
    </html>
  );
}
